import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import AOSProvider from "./AOSProvider";
import CursorWrapper from "@/components/cursor";
import Navbar from "@/components/navbar";
import "./globals.css";
import { cn } from "@/lib/utils";

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "EgarWorks.",
  // description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, "font-sans", inter.variable)}
    >
      <body className="min-h-full flex flex-col m-0 p-0 bg-black">
        <AOSProvider>
          <CursorWrapper />
          <Navbar />
          {children}
        </AOSProvider>
      </body>
    </html>
  );
}
