import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import AOSProvider from "./AOSProvider";
import DotPattern from "@/components/ui/dot-pattern";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import "./globals.css";
import { cn } from "@/lib/utils";

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "EgarWorks.",
  // description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, "font-sans", inter.variable)}
    >
      <body className="m-0 p-0 relative">
        <DotPattern />
        <AOSProvider>
          <Navbar />
          {children}
        </AOSProvider>
        <Footer />
        <div className="absolute -z-50 bottom-0 w-full h-[30rem] bg-gradient-to-t from-[rgb(0,13,36)] to-[rgba(0,30,80,0)]"></div>
      </body>
    </html>
  );
}
