import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AOSProvider from "./AOSProvider";
import DotPattern from "@/components/ui/dot-pattern";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import "./globals.css";
import { cn } from "@/lib/utils";

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

export const metadata: Metadata = {
  title: "EGARWORKS",
  // description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", "font-sans", inter.variable)}
    >
      <body className="m-0 p-0 overflow-x-hidden">
        <DotPattern />
        <AOSProvider>
          <Navbar />
          {children}
        </AOSProvider>
        <Footer />
      </body>
    </html>
  );
}
